# Generated by Django 2.0.6 on 2019-02-25 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('age', models.DecimalField(decimal_places=3, max_digits=7)),
                ('dob', models.DateTimeField(default=datetime.datetime(2019, 2, 25, 14, 24, 58, 859023, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('county', models.CharField(default='', max_length=200)),
                ('students', models.IntegerField(default=0)),
                ('dateOpened', models.DateField(default='')),
            ],
        ),
    ]
